### ISSUE TITLE
Doc needs update on data retrieval

### ISSUE THREAD

**Issue by pbougue** [CanalTP/tartare#68]
The doc https://github.com/CanalTP/tartare/blob/master/documentation/openAPI.yaml#L167
does not seem up-to-date with code https://github.com/CanalTP/tartare/blob/master/tartare/api.py#L52

(But I didn't test it/see it work so it might change)

**Comment by prhod** [comment]
I think it's a doc issue, the environment is mandatory to select the data to be retrived.

**Comment by pbougue** [comment]
Done :)
